### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mikeygio10** [TheRealKizu/SkyBlockUI#14]
**Describe the bug**

**To Reproduce**
It does not work at all

**Expected behavior**
type /isui and nothing pops up

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikeygio10** [comment]
Redskyblock does not work ether the server just shutts off and says cant find plugin redskyblock but its set to true so idk

**Comment by TheRealKizu** [comment]
Hello, RedSkyBlock is not yet done and if the plugin doesn't work, please download the latest stable release at [releases](https://github.com/TheRealKizu/SkyBlockUI/releases)

**Comment by TheRealKizu** [comment]
Also, an invalid issue description.
