### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Bennitenni111** [TheRealKizu/SkyBlockUI#26]
Whenever i manage members, or invite someone and click submit i get the error

**Comment by TheRealKizu** [comment]
Send the error.

**Comment by TheRealKizu** [comment]
Issue closed due to inactivity.

**Comment by Bennitenni111** [comment]
I get internal server error, and i get exited out
thats all happen

**Comment by TheRealKizu** [comment]
You really just replied after 4 months bruh
