### ISSUE TITLE
Redskyblock

### ISSUE THREAD

**Issue by jennocool** [TheRealKizu/SkyBlockUI#5]
Can you adjust it for redskyblock because I think redskyblock is better

**Comment by TheRealKizu** [comment]
I will in the future :). I'm busy right now on my school projects and my server

**Comment by TheRealKizu** [comment]
Duplicate of #3

**Comment by jennocool** [comment]
nice ;)

**Comment by TheRealKizu** [comment]
Progress can be found on the redsb branch ;)

**Comment by TheRealKizu** [comment]
Also chat now on #3
